version: "3.9"

services:
  db:
    container_name: cubi_db
    image: postgres
    volumes:
      - ./db_data:/data/cubicasa_test
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: cubicasa
      POSTGRES_PASSWORD: cubicasa
      POSTGRES_DB: cubicasa_test
      PGDATA: /data/cubicasa_test

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    links:
      - db
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  app:
    container_name: cubi_app
    image: golang:latest
    volumes:
      - ./backend:/go/src/backend
      - ./go:/go
    environment:
      - GOPATH=/go
      - GO111MODULE=on
      - APP_PORT=8080
      - PGSQL_HOST=db
      - PGSQL_DB=cubicasa_test
      - PGSQL_USERNAME=cubicasa
      - PGSQL_PASSWORD=cubicasa
      - BASIC_AUTH_USERNAME=cubicasa
      - BASIC_AUTH_PASSWORD=cubicasa
    ports:
      - 8000:8080
    tty: true
    links:
      - db
    command: bash -c "
        cd /go/src/backend/
        && apt install make
        && make install
        && make mod
        && go run cmd/main.go
      "